---
title: "writing_functions"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 7,
  fig.asp = .6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_color_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Z scores
```{r}
x_vec = rnorm(25, mean = 5, sd = 4)

(x_vec - mean(x_vec)) / sd(x_vec)

z_scores = function(x){
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
   
}

z_scores(x = x_vec)

y_vec = rnorm(40, mean = 12, sd = .3)

z_scores(y_vec)
```


let's try again

```{r}
z_scores = function(x){
  
  if(!is.numeric(x)){
    stop("x needs to be numeric")
  }
  
  if(length(x) <3){
    stop("x should have at least 3 numbers")
  }
  
  z = (x - mean(x)) / sd(x)
  
  return(z)
}
```

```{r, error = TRUE}
z_scores(3)

z_scores(c("my", "name", "is", "jeff"))

z_scores(mycars)

z_scores(y_vec)

```


# Multiple outputs
```{r}
mean_and_sd = function(x){
  
  if(!is.numeric(x)){
    stop("x needs to be numeric")
  }
  
  if(length(x) < 3){
    stop("x should have at least 3 numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  output_df = 
    tibble(
      mean = mean_x,
      sd = sd_x
    )
 
  return(output_df)
}

mean_and_sd(y_vec)
mean_and_sd(x_vec)
```

